copy C:\Users\Joe\git\AI1_Projects\SquaresPuzzle\src\ai1\squares\*.java "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Assignment1\source"
copy C:\Users\Joe\git\AI1_Projects\SquaresPuzzle\*.txt "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Assignment1\source"
copy C:\Users\Joe\git\AI1_Projects\SquaresPuzzle\*.html "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Assignment1\source"
copy C:\Users\Joe\git\AI1_Projects\SquaresPuzzle\*.bat "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Assignment1\source"
copy C:\Users\Joe\git\AI1_Projects\SquaresPuzzle\*.csv "C:\Users\Joe\Google Drive\School\Courses\AI1-480\Assignment1\source"
